### ISSUE TITLE
Use imagePullSecrets if required

### ISSUE THREAD

**Issue by estahn** [estahn/k8s-image-swapper#19]
We currently rely on the registry being public. If `imagePullSecrets` is specified, this should be used for authentication.

- [x] Image pull secrets from `Pod` ( see [docs](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/))
- [x] Image pull secrets from `ServiceAccount` (see [docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account))
- [ ] Use informer to monitor secret changes

**Comment by jurgen-weber-deltatre** [comment]
this would be amazing... :)

**Comment by DolevAlgam** [comment]
Hey @estahn ,
Great work on this project!
Mirroring from private repos would help us too.
Do you have an estimate on the next version outdate?
Are you aware of any forks that started resolving this issue?
We are considering forking and implementing this ourselves, depending on your answers to my questions above.￼
Thank You!

**Comment by estahn** [comment]
@DolevAlgam Thanks. I started updating the dependencies last week (mainly `slok/kubewebhook v1 -> v2`). I can look into this issue potentially this week.

If you have resources to implement this and like to contribute I'm accepting PRs.

**Comment by DolevAlgam** [comment]
Cool.
When you say 

> If imagePullSecrets is specified, this should be used for authentication.
Do you mean the imagePullSecrets field of the pods being deployed on the cluster or the imagePullSecrets field of the service account deployed for the k8s-image-swapper?

**Comment by estahn** [comment]
@DolevAlgam Ideally both, but I assume the `ServiceAccount` scenario is more complex.

**Comment by DolevAlgam** [comment]
@estahn a PR for using the Pull Secrets defined in the pod for pulling its source image will be created in the following days.

**Comment by estahn** [comment]
> @estahn a PR for using the Pull Secrets defined in the pod for pulling its source image will be created in the following days.

That's good news. I'm on vacation for the next few weeks in remote locations. Will pick this up as soon as I can.

**Comment by DolevAlgam** [comment]
> > @estahn a PR for using the Pull Secrets defined in the pod for pulling its source image will be created in the following days.
> 
> That's good news. I'm on vacation for the next few weeks in remote locations. Will pick this up as soon as I can.

No Problem :)
PR #92 has been created.

**Comment by estahn** [comment]
@DolevAlgam Just FYI, I'm back from vacation and will have a look at it in the next couple of days.

**Comment by DolevAlgam** [comment]
@estahn Hey,
Did you have the time to check out the PR?
Thanks.

**Comment by estahn** [comment]
> @estahn Hey,
> Did you have the time to check out the PR?
> Thanks.

I have just pushed the update for [slok/kubewebhook](https://github.com/estahn/k8s-image-swapper/commit/8bd73d47772c0524c552577805d9f01ae365e77f). Would you mind resolving the conflicts?

**Comment by DolevAlgam** [comment]
Hey @estahn, I resolved the conflicts :)
Tell me if you need anything else.

**Comment by yaron-idan** [comment]
Hey @estahn,
First off, thanks for writing this tool, it really helps us deal with registry outages.
We'd really like to see this issue resolved so we can use the image swapper with private registries as well, could you help us push the PR @DolevAlgam created forward?
Thanks!

**Comment by estahn** [comment]
@DolevAlgam I have updated the helm chart to allow access to secrets. Would you mind testing if this is working for you?

**Comment by DolevAlgam** [comment]
@estahn Sure thing! Can it wait till Wednesday next week? We’re all at a company trip :)

**Comment by estahn** [comment]
@DolevAlgam Yes, of course, it can wait. Enjoy your trip :)

**Comment by DolevAlgam** [comment]
Thanks!
