### ISSUE TITLE
Question regarding private repository URLs and ports.

### ISSUE THREAD

**Issue by mvchris** [estahn/k8s-image-swapper#405]
We're using k8s-image-swapper in conjunction with GitLab CI. GitLab provides a dependency proxy service, basically a Docker pull-through cache for images used during builds. The registry URL starts with `gitlab.com:443`, which cannot be translated to an AWS ECR repository name (doesn't allow colons).

Is this handled in the code (I don't seem to be able to find a registry normalization function) and if so what is a registry URL that includes a port translated into?

**Comment by estahn** [comment]
@mvchris I don't quite understand the issue, could you further elaborate? Do you have any error messages?

Is this something that would resolve your issue?
https://github.com/estahn/k8s-image-swapper/pull/394

**Comment by estahn** [comment]
I haven't received any further information on this. Going to close it. Feel free to reopen it.
