### ISSUE TITLE
Support fallback registries

### ISSUE THREAD

**Issue by shaikatz** [estahn/k8s-image-swapper#43]
I want to be able to specify 2 regions for my ECR, in case one of them is down.
Always copy to both, but use the first priority one for the actual replacement if it's up.

**Comment by estahn** [comment]
Interesting idea. There is already [cross-region replication for ECR](https://aws.amazon.com/blogs/containers/cross-region-replication-in-amazon-ecr-has-landed/) but you would have to manually adjust the account ID in the swapper.

**Comment by estahn** [comment]
@shaikatz Do you think cross-region replication for ECR solves your use case or do you still see the need for this?

**Comment by shaikatz** [comment]
Cross-region replication sounds like a good solution for that use case, I'll close the issue now.
