### ISSUE TITLE
Docker references with both a tag and digest are currently not supported

### ISSUE THREAD

**Issue by shaikatz** [estahn/k8s-image-swapper#48]
Hi,
Receiving the titled error when using image that includes tags and digest like `k8s.gcr.io/ingress-nginx/controller:v0.43.0@sha256:9bba603b99bf25f6d117cf1235b6598c16033ad027b143c90fa5b3cc583c5713`

Where this limitation is coming from? can't ECR support digest?
Can we somehow overcome that so the tool will support that?

**Comment by bradonkanyid** [comment]
I've followed this to the source and found that the upstream library won't support images with tags and digests. That issue is here: https://github.com/containers/image/issues/783

CRI-O had to implement their own behavior to fix, here: https://github.com/cri-o/cri-o/pull/3060

**Comment by bradonkanyid** [comment]
My mistake: here's `containers/image` explicitly stating they won't support this: https://github.com/containers/image/pull/1019
