### ISSUE TITLE
Check if image exists in ECR

### ISSUE THREAD

**Issue by estahn** [estahn/k8s-image-swapper#51]
The current implementation only checks if it's available via in-memory cache. If it is not then a download will be initiated – which effectively only syncs the latest layers. But ideally, no download should be initiated as this seems to count towards the rate-limiting of some providers.

**Comment by krmichelos** [comment]
Does this change address this issue by adding a break in the workflow if the image is already in the target repo?
https://github.com/estahn/k8s-image-swapper/commit/a133c782be4e3001a9ce829c50fd7ae79c0a4c75

**Comment by estahn** [comment]
From practical experience this does not appear to be an issue. If so, I will reopen it.
