### ISSUE TITLE
feat: Allow for image blacklists

### ISSUE THREAD

**Issue by arihantsurana** [estahn/k8s-image-swapper#55]
We might want to not swap some images, please allow to blacklist these.

**Comment by estahn** [comment]
@arihantsurana Hi Ari, I believe this should already be possible. Are [source filters](https://estahn.github.io/k8s-image-swapper/configuration.html#filters) not working for you?

**Comment by estahn** [comment]
@arihantsurana I'm closing this. Feel free to reopen.
