### ISSUE TITLE
ecrOptions.imageTagMutability doesn't work

### ISSUE THREAD

**Issue by mikebryant** [estahn/k8s-image-swapper#649]
We've set this to `IMMUTABLE`, but it's still created as MUTABLE

It's configurable here: https://github.com/estahn/k8s-image-swapper/blob/369ac7c53f65cbb98c92e73cba21714c2d67d19e/pkg/config/config.go#L82

But hardcoded here: https://github.com/estahn/k8s-image-swapper/blob/369ac7c53f65cbb98c92e73cba21714c2d67d19e/pkg/registry/ecr.go#L114

**Comment by estahn** [comment]
@mikebryant Good find. Would you mind contributing a PR for this?
