### ISSUE TITLE
Mutate initContainers

### ISSUE THREAD

**Issue by estahn** [estahn/k8s-image-swapper#73]
k8s-image-swapper is currently not handling `initContainers`.

**Comment by asad-awadia** [comment]
@estahn https://github.com/estahn/k8s-image-swapper/pull/96 how does this look?

**Comment by asad-awadia** [comment]
@estahn ping

**Comment by estahn** [comment]
@asad-awadia Thanks for the contribution. I just came back from an extended vacation and catching up with things. Will look at this shortly.

**Comment by asad-awadia** [comment]
@estahn Ok np - Lmk how the PR looks - if any changes required
